version: '3'

services:
  api:
    container_name: 'poke_trade_api'
    image: api_poke
    restart: always
    environment:
      - PORT=5000
    ports:
      - '5000:5000'
    build:
      context: .
      dockerfile: Dockerfile
